# Generated by Django 6.1.1 on 2026-09-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, verbose_name="Image d'illustration (URL)")),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie Culinaire',
                'verbose_name_plural': 'Catégories Culinaires',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'établissement")),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Slogan / Spécialité phare')),
                ('description', models.TextField(verbose_name='Présentation authentique')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone de commande')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('city', models.CharField(default='Douala', max_length=50, verbose_name='Ville')),
                ('neighborhood', models.CharField(max_length=120, verbose_name='Quartier')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse physique & repères')),
                ('latitude', models.FloatField(default=4.051056, verbose_name='Latitude GPS')),
                ('longitude', models.FloatField(default=9.708535, verbose_name='Longitude GPS')),
                ('cover_image', models.URLField(verbose_name='Bannière du restaurant (URL)')),
                ('logo_image', models.URLField(blank=True, verbose_name='Logo ou façade (URL)')),
                ('price_range', models.CharField(choices=[('$', 'Économique (< 2 000 FCFA)'), ('$$', 'Moyen (2 000 - 5 000 FCFA)'), ('$$$', 'Gastronomique (> 5 000 FCFA)')], default='$$', max_length=5, verbose_name='Gamme de prix')),
                ('opening_time', models.TimeField(default='10:30', verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(default='22:30', verbose_name='Heure de fermeture')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert aux commandes actuellement')),
                ('is_approved', models.BooleanField(default=True, verbose_name="Validé par l'administration")),
                ('delivery_fee', models.PositiveIntegerField(default=1000, verbose_name='Frais de livraison de base (FCFA)')),
                ('min_order_amount', models.PositiveIntegerField(default=2000, verbose_name='Montant minimum de commande (FCFA)')),
                ('estimated_delivery_time', models.CharField(default='35 - 50 min', max_length=50, verbose_name='Délai estimé de livraison')),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3, verbose_name='Note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=12, verbose_name="Nombre d'avis")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='restaurants', to='restaurants.category', verbose_name='Catégories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire / Gérant')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du plat')),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(verbose_name='Description détaillée des ingrédients et saveurs')),
                ('price', models.PositiveIntegerField(verbose_name='Prix unitaire (FCFA)')),
                ('image', models.URLField(verbose_name='Photo réelle du plat (URL)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible en cuisine')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Plat du Chef / Populaire')),
                ('prep_time_minutes', models.PositiveIntegerField(default=25, verbose_name='Temps de préparation (min)')),
                ('spice_level', models.CharField(choices=[('doux', 'Doux (Sans piment piquant)'), ('moyen', 'Piment moyen (Rehaussé au pèbè & rondelles)'), ('releve', 'Relevé (Piment jaune du village)'), ('fort', 'Très fort (Piment oiseau camerounais pur)')], default='moyen', max_length=20, verbose_name="Niveau d'épices")),
                ('authentic_origin', models.CharField(choices=[('Littoral (Sawa)', 'Littoral / Terroir Sawa (Wouri, Moungo, Sanaga)'), ('Ouest (Bamiléké)', 'Ouest / Terroir Grassfields & Bamiléké'), ('Centre & Sud (Beti)', 'Centre, Sud & Est / Terroir Beti & Fang'), ('Nord (Sahel)', 'Grand Nord / Sahel (Soya, Kilichi, Boule)'), ('Sud-Ouest (Côte)', 'Sud-Ouest & Anglophone (Eru, Achu, Koki)'), ('Pan-Africain', 'Grillades & Boissons artisanales')], default='Littoral (Sawa)', max_length=60, verbose_name='Origine régionale')),
                ('sides_included', models.CharField(default='Plantains mûrs frits (alloco/dodo), miondo ou manioc vapeur', max_length=200, verbose_name='Accompagnements au choix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='restaurants.category', verbose_name='Catégorie')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['-is_featured', 'price', 'name'],
            },
        ),
    ]
