# Generated by Django 6.1.1 on 2026-09-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='product_type',
            field=models.CharField(choices=[('plat', 'Plat principal du terroir'), ('boisson', 'Boisson & Rafraîchissement'), ('entree', 'Entrée / Amuse-bouche'), ('dessert', 'Dessert / Douceur')], default='plat', max_length=20, verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sides_included',
            field=models.CharField(blank=True, default='Plantains mûrs frits (alloco/dodo), miondo ou manioc vapeur', max_length=200, verbose_name='Accompagnements au choix'),
        ),
    ]
