# Generated by Django 6.1.1 on 2026-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_dish_product_type_alter_dish_sides_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis"),
        ),
    ]
