# Generated by Django 6.1.1 on 2026-09-28 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['-is_featured', 'product_type', 'price', 'name'], 'verbose_name': 'Produit / Plat', 'verbose_name_plural': 'Produits & Plats'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant (Singleton)', 'verbose_name_plural': 'Restaurant (Singleton)'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_zone',
            field=models.CharField(default='Douala (Akwa, Bonapriso, Deido, Bonamoussadi, Bali, Bépanda, Makepe)', max_length=255, verbose_name='Zone de livraison couverte'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, default='', verbose_name='Photo réelle du plat (URL)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom du produit / plat'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sides_included',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Accompagnements inclus ou au choix'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse physique & repères précis'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.category', verbose_name='Spécialités couvertes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='Bannière principale (URL)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=1000, verbose_name='Frais de livraison forfaitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(verbose_name='Présentation authentique du restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Établissement actif'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_image',
            field=models.URLField(blank=True, verbose_name='Logo du restaurant (URL)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='RestoGourmand', max_length=150, verbose_name='Nom du restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='neighborhood',
            field=models.CharField(default='Akwa', max_length=120, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Restaurateur / Gérant assigné'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Téléphone de contact & commandes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan / Identité culinaire'),
        ),
    ]
