# Generated by Django 6.1.1 on 2026-09-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_dish_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Fichier photo téléversé'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Photo réelle du plat (URL ou chemin)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Le Gout', max_length=150, verbose_name='Nom du restaurant'),
        ),
    ]
