# Generated by Django 6.1.1 on 2026-09-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=60, unique=True, verbose_name='Identifiant unique de transaction')),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money Cameroun'), ('cinetpay', 'CinetPay Gateway'), ('cash', 'Paiement à la livraison (Cash)')], default='mtn_momo', max_length=30, verbose_name='Opérateur de paiement')),
                ('phone_number', models.CharField(help_text='Ex: 677... (MTN) ou 690... (Orange)', max_length=30, verbose_name='Numéro de compte débité')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant débité (FCFA)')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', "En cours d'autorisation"), ('successful', 'Paiement validé avec succès'), ('failed', 'Transaction refusée ou interrompue'), ('cancelled', "Transaction annulée par l'utilisateur")], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Code de référence opérateur / Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date & Heure')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
