# Generated by Django 6.1.1 on 2026-09-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recherche_livreur', "Recherche d'un coursier à proximité"), ('assignee', 'Course acceptée par le livreur'), ('arrivee_restaurant', 'Livreur arrivé au restaurant'), ('recuperee', 'Colis chaud récupéré / En route'), ('arrivee_client', 'Livreur sur le pas de porte'), ('livree', 'Course terminée & confirmée'), ('echec', 'Échec ou annulation de livraison')], default='recherche_livreur', max_length=30, verbose_name='Statut de la course')),
                ('driver_phone', models.CharField(blank=True, max_length=30, verbose_name='Contact direct du livreur')),
                ('pickup_address', models.CharField(blank=True, max_length=255, verbose_name='Adresse de départ (Restaurant)')),
                ('pickup_latitude', models.FloatField(default=4.051056, verbose_name='Lat. Restaurant')),
                ('pickup_longitude', models.FloatField(default=9.708535, verbose_name='Long. Restaurant')),
                ('dropoff_address', models.CharField(blank=True, max_length=255, verbose_name="Adresse d'arrivée (Client)")),
                ('dropoff_latitude', models.FloatField(default=4.0485, verbose_name='Lat. Client')),
                ('dropoff_longitude', models.FloatField(default=9.698, verbose_name='Long. Client')),
                ('current_latitude', models.FloatField(default=4.05, verbose_name='Lat. Actuelle Coursier')),
                ('current_longitude', models.FloatField(default=9.705, verbose_name='Long. Actuelle Coursier')),
                ('distance_km', models.FloatField(default=3.8, verbose_name='Distance calculée (km)')),
                ('estimated_duration_min', models.PositiveIntegerField(default=25, verbose_name='Durée estimée (minutes)')),
                ('driver_payout', models.PositiveIntegerField(default=800, verbose_name='Gain net coursier (FCFA)')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de prise en charge')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ restaurant')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure effective de remise')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Livreur assigné')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_mission', to='orders.order', verbose_name='Commande associée')),
            ],
            options={
                'verbose_name': 'Course de livraison',
                'verbose_name_plural': 'Courses de livraison',
                'ordering': ['-order__created_at'],
            },
        ),
    ]
