# Generated by Django 6.1.1 on 2026-09-28 07:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Doit changer de mot de passe à la première connexion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client Gourmand'), ('restaurateur', 'Restaurateur / Gérant'), ('livreur', 'Livreur Partenaire'), ('admin', 'Administrateur Plateforme'), ('restaurant', 'Restaurateur (Legacy)'), ('driver', 'Livreur (Legacy)')], default='client', max_length=20, verbose_name='Rôle utilisateur'),
        ),
    ]
