# Generated by Django 6.1.1 on 2026-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0, help_text="Solde de démonstration de 10 000 FCFA offert à l'inscription", verbose_name='Solde portefeuille simulé (FCFA)'),
        ),
    ]
