# Generated by Django 6.1.1 on 2026-09-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 étoile - Très décevant'), (2, '2 étoiles - Passable'), (3, '3 étoiles - Bon'), (4, '4 étoiles - Très bon'), (5, '5 étoiles - Excellent terroir')], default=5, verbose_name='Note sur 5')),
                ('comment', models.TextField(verbose_name="Commentaire d'expérience culinaire")),
                ('is_verified_purchase', models.BooleanField(default=True, verbose_name='Commande vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to=settings.AUTH_USER_MODEL, verbose_name="Auteur de l'avis")),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='restaurants.dish', verbose_name='Plat spécifique (optionnel)')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order', verbose_name='Commande vérifiée')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant', verbose_name='Restaurant noté')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
