# Generated by Django 6.1.1 on 2026-09-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, unique=True, verbose_name='N° de commande')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de validation'), ('confirmee', 'Confirmée par le restaurant'), ('en_preparation', 'En cours de préparation en cuisine'), ('prete', 'Prête / En attente du livreur'), ('en_livraison', "En cours d'acheminement"), ('livree', 'Livrée au client'), ('annulee', 'Annulée')], default='en_attente', max_length=30, verbose_name='Statut de la commande')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Sous-total plats (FCFA)')),
                ('delivery_fee', models.PositiveIntegerField(default=1000, verbose_name='Frais de livraison (FCFA)')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Total à payer (FCFA)')),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money (*126#)'), ('orange_money', 'Orange Money (*150#)'), ('cinetpay', 'CinetPay (Passerelle sécurisée / Carte)'), ('cash_on_delivery', 'Paiement en espèces à la livraison')], default='mtn_momo', max_length=30, verbose_name='Mode de règlement')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échec'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='État du paiement')),
                ('delivery_city', models.CharField(default='Douala', max_length=50, verbose_name='Ville de livraison')),
                ('delivery_neighborhood', models.CharField(max_length=120, verbose_name='Quartier de livraison')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Adresse / Rue')),
                ('delivery_landmark', models.CharField(help_text='Ex: Face pharmacie de la Paix, à côté du grand manguier', max_length=255, verbose_name='Repère de proximité')),
                ('delivery_phone', models.CharField(max_length=30, verbose_name='Numéro de contact pour livraison')),
                ('client_notes', models.TextField(blank=True, verbose_name='Consignes spéciales de dégustation ou de livraison')),
                ('delivery_pin', models.CharField(default='1234', max_length=4, verbose_name='Code PIN de confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Nom du plat')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Prix unitaire (FCFA)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Sous-total (FCFA)')),
                ('selected_side', models.CharField(blank=True, max_length=150, verbose_name='Accompagnement sélectionné')),
                ('special_instructions', models.CharField(blank=True, max_length=255, verbose_name='Remarques (ex: bien pimenté, sauce à part)')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurants.dish', verbose_name='Plat commandé')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
