# Generated by Django 6.1.1 on 2026-09-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Livraison à domicile'), ('pickup', 'À emporter / Retrait au restaurant')], default='delivery', max_length=20, verbose_name='Mode de réception'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse / Rue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_landmark',
            field=models.CharField(blank=True, default='', help_text='Ex: Face pharmacie de la Paix, à côté du grand manguier', max_length=255, verbose_name='Repère de proximité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_neighborhood',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Quartier de livraison'),
        ),
    ]
