# Generated by Django 6.1.1 on 2026-09-28 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type_alter_order_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Solde Portefeuille Simulé (10 000 FCFA Offerts)'), ('mtn_momo', 'MTN Mobile Money (*126#)'), ('orange_money', 'Orange Money (*150#)'), ('cinetpay', 'CinetPay (Passerelle sécurisée / Carte)'), ('cash_on_delivery', 'Paiement en espèces à la livraison')], default='mtn_momo', max_length=30, verbose_name='Mode de règlement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('payee', 'Payée - En attente de validation restaurant'), ('en_attente', 'En attente de validation'), ('validee', 'Validée par le restaurant'), ('confirmee', 'Confirmée par le restaurant'), ('en_preparation', 'En cours de préparation en cuisine'), ('prete', 'Prête / En attente du livreur'), ('en_livraison', "En cours d'acheminement"), ('livree', 'Livrée au client'), ('refusee', 'Refusée par le restaurant'), ('annulee', 'Annulée')], default='en_attente', max_length=30, verbose_name='Statut de la commande'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='N° de facture / Reçu')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom complet du client')),
                ('client_phone', models.CharField(max_length=40, verbose_name='Téléphone client')),
                ('delivery_type', models.CharField(max_length=30, verbose_name='Mode de réception')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Lieu de livraison ou retrait')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Sous-total plats (FCFA)')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='Frais de livraison (FCFA)')),
                ('total_amount', models.PositiveIntegerField(verbose_name='Total payé (FCFA)')),
                ('payment_method', models.CharField(max_length=60, verbose_name='Mode de règlement')),
                ('is_refunded', models.BooleanField(default=False, verbose_name='Statut remboursé')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='Commande associée')),
            ],
            options={
                'verbose_name': 'Facture / Reçu',
                'verbose_name_plural': 'Factures / Reçus',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notif_type', models.CharField(choices=[('order_created', 'Nouvelle commande'), ('order_validated', 'Commande validée par le restaurateur'), ('order_rejected', 'Commande refusée & Remboursée'), ('order_ready', 'Commande prête'), ('delivery_assigned', 'Nouvelle livraison disponible'), ('delivery_dispatched', 'Commande en cours de livraison'), ('order_delivered', 'Commande livrée'), ('refund', 'Remboursement'), ('info', 'Information')], default='info', max_length=30, verbose_name='Type de notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date & Heure')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='Commande associée')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
